# $FreeBSD: head/korean/libreoffice/Makefile 397662 2015-09-23 21:06:12Z jkim $

CATEGORIES=	korean
LO_I18N=	ko
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.i18n"

.include <bsd.port.mk>
