env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  timeout_in: 120m
  freebsd_instance:
    matrix:
#      image_family: freebsd-13-0-snap
      image_family: freebsd-12-1
    cpu: 8
    memory: 16G
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f; pkg update -f
    - pkg install -y poudriere git
  script:
    - ./porttest.sh
