env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  timeout_in: 120m
  compute_engine_instance:
    cpu: 8
    memory: 24g
    disk: 40
    image_project: freebsd-org-cloud-dev
    platform: freebsd
  matrix:
    - name: 13.0-RELEASE
      compute_engine_instance:
        image: family/freebsd-13-0
    - name: 12.2-RELEASE
      compute_engine_instance:
        image: family/freebsd-12-2
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y poudriere-devel git-tiny
  script:
    - ./porttest.sh
