# $FreeBSD: head/japanese/libreoffice/Makefile 397662 2015-09-23 21:06:12Z jkim $

CATEGORIES=	japanese
LO_I18N=	ja
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.i18n"

.include <bsd.port.mk>
