# $FreeBSD: head/arabic/libreoffice/Makefile 430266 2017-01-01 17:54:02Z jkim $

CATEGORIES=	arabic
LO_I18N=	ar
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.i18n"

.include <bsd.port.mk>
