# $FreeBSD: head/editors/libreoffice-lt/Makefile 430266 2017-01-01 17:54:02Z jkim $

LO_I18N=	lt
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.i18n"

.include <bsd.port.mk>
