# $FreeBSD: head/portuguese/libreoffice-pt_BR/Makefile 397662 2015-09-23 21:06:12Z jkim $

CATEGORIES=	portuguese
LO_I18N=	pt_BR
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.i18n"

.include <bsd.port.mk>
