# $FreeBSD: head/editors/libreoffice6/Makefile.common 553421 2020-10-27 07:46:27Z fluffy $

PORTNAME=	libreoffice
PORTVERSION=	6.4.7
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL20
LICENSE_COMB=	dual

LOVERSION=	${PORTVERSION}.${RCVER}
RCVER=		2
