# $FreeBSD: head/editors/libreoffice/Makefile.common 511270 2019-09-05 20:55:22Z lwhsu $

PORTNAME=	libreoffice
PORTVERSION=	6.3.2
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL20
LICENSE_COMB=	dual

LOVERSION=	${PORTVERSION}.${RCVER}
RCVER=		2
