# $FreeBSD: head/editors/libreoffice/Makefile.common 553614 2020-10-29 12:46:43Z fluffy $

PORTNAME=	libreoffice
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL20
LICENSE_COMB=	dual

DISTVERSION=	${LOVERSION}.${RCVER}
LOVERSION=	7.1.2
RCVER=		2

#PRERELEASE=	yes
#DEVRELEASE=	yes
