# $FreeBSD: head/editors/libreoffice/Makefile.common 453378 2017-11-02 21:12:58Z jkim $

PORTNAME=	libreoffice
PORTVERSION=	6.0.2
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL20
LICENSE_COMB=	dual

LOVERSION=	${PORTVERSION}.${RCVER}
RCVER=		1
