# $FreeBSD: head/vietnamese/libreoffice/Makefile 397662 2015-09-23 21:06:12Z jkim $

CATEGORIES=	vietnamese
LO_I18N=	vi
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.i18n"

.include <bsd.port.mk>
